sudo: false
language: java
jdk:
  - oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: change

after_success: 
  - ./gradlew publish --rerun-tasks -PbintrayUsername=$BINTRAY_USERNAME -PbintrayPassword=$BINTRAY_API_KEY
